services:
  front:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_BASE_URL: "https://sandbox.thibaud-cb.fr"
    container_name: activscanio-front
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: "https://sandbox.thibaud-cb.fr"
