services:
  front:
    container_name: activscanio-front
    build:
      context: .
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    ports:
      - "3001:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
